FROM alpine:3.5 AS alpine_image

RUN apk add
RUN apk add --no-cache python2
RUN apk add --update py2-pip
RUN apk update && \
    apk add --update nodejs  && \
    npm install newman --global
WORKDIR /project/flask-app

COPY flask-app /project/flask-app

RUN pip install -r requirements.txt



#COPY flask-app /project/flask-app

# expose port
EXPOSE 5000

# start app
CMD [ "python", "./app.py" ]


