version: "3"
services:

  frontend:
    build: ./flask-app/
    container_name: nginx_app
    ports: 
      - "80:80"
    depends_on: 
      - app
    volumes: 
      #- ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks: 
      - frontend
    


  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    container_name: es
    environment:
      - discovery.type=single-node
    #ports:
     # - 9200:9200
    #volumes:
     # - esdata1:/usr/share/elasticsearch/data
    networks: 
      - backend


  app:
    build: .
    command: python app.py
    depends_on:
      - es
    ports:
      - 5000:5000
    #volumes:
      #- ./flask-app:/project/flask-app
    networks: 
      - frontend
      - backend

volumes:
    esdata1:

networks: 
   frontend:
   backend: